# Generated by Django 3.0.6 on 2020-06-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserch',
            new_name='Research',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='research_photos'),
        ),
    ]
