# Generated by Django 3.0.7 on 2020-06-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0002_auto_20200608_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='equiptment',
            new_name='research',
        ),
    ]
