# Generated by Django 3.0.6 on 2020-06-09 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20200608_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiptment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equiptment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
