# Generated by Django 3.0.6 on 2020-06-09 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='link')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='publications.Publication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
