# Generated by Django 3.0.7 on 2020-06-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20200616_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='publications.Publication'),
        ),
    ]
