# Generated by Django 3.0.6 on 2020-06-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeResearchInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipatingSociety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Participating Societies',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('adress', models.CharField(default='', max_length=80)),
                ('email', models.CharField(default='', max_length=20)),
                ('contact_number', models.CharField(default='', max_length=20)),
                ('description', models.TextField(default='')),
                ('cooperative_research_institutions', models.ManyToManyField(blank=True, related_name='Description', to='descriptions.CooperativeResearchInstitution')),
                ('participating_societies', models.ManyToManyField(blank=True, related_name='Description', to='descriptions.ParticipatingSociety')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
