# Generated by Django 3.0.6 on 2020-06-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='participating_society',
            new_name='participating_societies',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='reserch_area',
            new_name='reserch_areas',
        ),
    ]
