# Generated by Django 3.0.6 on 2020-06-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0002_auto_20200602_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='description',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='resercharea',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
