# Generated by Django 3.0.6 on 2020-06-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0003_auto_20200602_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='resercharea',
            name='description',
            field=models.TextField(default=True),
        ),
    ]
