# Generated by Django 3.0.6 on 2020-06-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0005_auto_20200602_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeResearchInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='description',
            name='adress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='description',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='description',
            name='cooperative_research_institutions',
            field=models.ManyToManyField(blank=True, related_name='Description', to='descriptions.CooperativeResearchInstitution'),
        ),
    ]
