# Generated by Django 3.0.6 on 2020-06-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0006_auto_20200602_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='adress',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='description',
            name='email',
            field=models.TextField(default='', max_length=20),
        ),
    ]
