# Generated by Django 3.0.6 on 2020-06-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0008_auto_20200602_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
