# Generated by Django 3.0.6 on 2020-06-02 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0009_description_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='number',
            new_name='contact_number',
        ),
    ]
