# Generated by Django 3.0.6 on 2020-06-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars')),
                ('description', models.TextField()),
            ],
        ),
    ]
