# Generated by Django 3.0.7 on 2020-06-18 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200617_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='members.Member'),
        ),
    ]
